name: Build and Test with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Cambié de adoptopenjdk a temurin

      - name: Compile with Maven
        run: mvn clean compile -B

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Cambié de adoptopenjdk a temurin

      - name: Run unit tests
        run: mvn test -B

      - name: Upload test results
        uses: actions/upload-artifact@v3  # Cambié a la versión v2 de upload-artifact
        with:
          name: test-results
          path: target/surefire-reports/TEST-*.xml
